### ISSUE TITLE
normalization_extra_whitespace causes whitespace loss in data

### ISSUE THREAD

**Issue by rf152** [dolejska-daniel/amcp-pylib#1]
I am passing data that is in Markdown format, and the normalization_extra_whitespace function is removing double spaces at the end of lines.

Is there a way of igoring the data part of the command when normalizing the whitespace in the command?

**Comment by dolejska-daniel** [comment]
This normalization procedure is present for cosmetic reasons only and is therefore not required at all. I will remove it promply 😄

**Comment by dolejska-daniel** [comment]
Hey, latest version is now available at https://pypi.org/project/amcp-pylib/0.2.1/! Hope this helps ☺️ 

PS: I'm sorry - I might have caused some incompatibility with your current implementation. It should be pretty straightforward to fix tho, no core concept has changed - response classes have been moved to different directory and some response related classes renamed!
