### ISSUE TITLE
v0.2.1 CG ADD no space between layer and ADD keyword

### ISSUE THREAD

**Issue by rf152** [dolejska-daniel/amcp-pylib#3]
When calling CG_ADD, it is misformatting the command:

`CG 1-20ADD 20 "template/template" 1 "{}"`

which should be 

`CG 1-20 ADD 20 "template/template" 1 "{}"`

**Comment by dolejska-daniel** [comment]
This issue should be fixed now in `v.0.2.2` version. This version should also be already available via `pip`.
