### ISSUE TITLE
Example of use with CG_ADD

### ISSUE THREAD

**Issue by miambe** [dolejska-daniel/amcp-pylib#7]
I don't know what I miss but I'm unable to use the `CG_ADD` command.

I've tried:
```python
response = client.send(CG_ADD("CG 1 ADD 0 COUNTDOWN 1"))
```

And I'm getting:
```
RuntimeError: Command functions do not accept any positional arguments.
```

Thanks for your help!

**Comment by dolejska-daniel** [comment]
Hello, and thank you for your interest in this library!
The commands expect their parameters to be provided by keyword arguments. For example, with the [`CG_ADD`](https://github.com/dolejska-daniel/amcp-pylib/blob/master/amcp_pylib/module/template.py#L4-L11) command's syntax looking like this:
```
CG [video_channel:int]{-[layer:int]|-9999} ADD [cg_layer:int] [template:string] [play_on_load:0,1] {[data:string]}
```

This syntax description defines following variables:
  - `video_channel`
  - `layer`
  - `cg_layer`
  - `template`
  - `play_on_load`
  - `data`

These variables can then be assigned to using corresponding keyword arguments:
```python
# for your given example "CG 1 ADD 0 COUNTDOWN 1"
command = CG_ADD(video_channel=1, cg_layer=0, template="COUNTDOWN", play_on_load=1)
```

After creating the command like that, you can send the command using `client.send(command)` as you have shown before. The program will create appropriate CasparCG command syntax on its own.

**Comment by miambe** [comment]
Thanks for your quick reply!
It works as expected.
